apiVersion: apps/v1
kind: Deployment # change here
metadata:
  name: nlp-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nlp-api
  template:
    metadata:
      labels:
        app: nlp-api
    spec:
      containers:
      - image: ghcr.io/nhthien/nlp_api:k8s
        name: nlp-api
        imagePullPolicy: Always
        ports:
          - containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: nlp-api-nodeport
spec:
  type: NodePort
  selector:
    app: nlp-api
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 31000