name: Deploy nlp_api develop
on:
  push:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        logout: false
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push the Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        file: Dockerfile
        tags: |
          nlp_api:${{ github.sha }}
          nlp_api:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
